apiVersion: v1
kind: Service
metadata:
  name: nginx-replicaset-service1
spec:
  type: NodePort
  selector:
    name: nginx-replicaset
  ports:
    - nodePort: 31072
      port: 80
      protocol: TCP
      targetPort: 80
