apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    name: nginx-server
    role: blue
  ports:
    - nodePort: 31072
      port: 80
      protocol: TCP
      targetPort: 80